import { useState, useMemo, useEffect } from 'react'
import {
  CheckCircle2, XCircle, Link2, Sparkles, Pencil, Check, X as XIcon,
  ExternalLink, Package, Building2,
} from 'lucide-react'
import { supabase } from '../supabaseClient'
import { useTable } from '../lib/db'
import { useAuth } from '../lib/auth'
import {
  PageHeader, Card, Button, Empty, LoadingBlock, ErrorBlock, Badge,
  inputCls, normaliseError,
} from '../components/UI'

/**
 * Match Review — two review queues on one page:
 *
 *   1. AUTO-FOUND URLs — competitor_products created by the URL finder
 *      with match_method='auto'. Admin/manager approves each, rejects
 *      (deletes the link), or edits the URL inline if it's wrong.
 *
 *   2. NAME-SIMILARITY suggestions — match_suggestions rows generated by
 *      the pg_trgm trigger when a competitor_products row is inserted
 *      WITHOUT a product_id (rare in practice; the finder always sets
 *      product_id).
 */
export default function MatchReview() {
  const { isManager } = useAuth()

  // Auto-found URLs pending review
  const { rows: autoLinks, loading: aL, refresh: refreshAuto } = useTable('competitor_products', {
    eq: ['match_method', 'auto'],
    order: ['created_at', { ascending: false }],
  })
  // Products + competitors for display
  const { rows: products } = useTable('products')
  const { rows: competitors } = useTable('competitors')
  // Legacy trigram suggestions
  const { rows: suggestions, loading: sL, error: sErr, refresh: refreshSug } = useTable('match_suggestions', {
    eq: ['reviewed', false],
    order: ['confidence', { ascending: false }],
  })

  const productById = useMemo(() => Object.fromEntries(products.map(p => [p.id, p])), [products])
  const competitorById = useMemo(() => Object.fromEntries(competitors.map(c => [c.id, c])), [competitors])

  return (
    <div>
      <PageHeader
        kicker="Human-in-the-loop"
        title="Match Review"
        subtitle="Approve auto-discovered competitor URLs and pg_trgm name matches before they affect pricing."
      />

      <ErrorBlock error={sErr} onRetry={refreshSug} />

      {/* ── Section 1: Auto-found URLs ─────────────────────── */}
      <Card className="mb-6 overflow-hidden">
        <div className="px-6 py-4 border-b border-ink-100 flex items-baseline justify-between">
          <div>
            <div className="text-[10px] uppercase tracking-[0.14em] font-semibold text-brand-700">Auto-discovery</div>
            <h3 className="font-display text-[20px] tracking-tight text-ink-900 mt-1">
              Auto-found competitor URLs — awaiting your approval
            </h3>
          </div>
          <div className="text-[11.5px] text-ink-500">
            {autoLinks.length} pending
          </div>
        </div>

        {aL ? <LoadingBlock text="Loading auto-found URLs" /> : autoLinks.length === 0 ? (
          <div className="py-12 text-center px-6">
            <CheckCircle2 size={32} className="text-emerald-500 mx-auto mb-3" strokeWidth={1.5} />
            <div className="font-display text-[17px] tracking-tight text-ink-900">All caught up</div>
            <div className="text-[12.5px] text-ink-500 mt-1">
              Nothing to review. Auto-found URLs appear here when the URL finder discovers a match.
            </div>
          </div>
        ) : (
          <div className="divide-y divide-ink-100">
            {autoLinks.map(link => (
              <AutoLinkRow
                key={link.id}
                link={link}
                product={productById[link.product_id]}
                competitor={competitorById[link.competitor_id]}
                isManager={isManager}
                onChanged={refreshAuto}
              />
            ))}
          </div>
        )}
      </Card>

      {/* ── Section 2: pg_trgm name suggestions ────────────── */}
      {suggestions.length > 0 && (
        <Card className="overflow-hidden">
          <div className="px-6 py-4 border-b border-ink-100">
            <div className="text-[10px] uppercase tracking-[0.14em] font-semibold text-ink-500">Name similarity</div>
            <h3 className="font-display text-[20px] tracking-tight text-ink-900 mt-1">
              Suggested product matches ({suggestions.length})
            </h3>
          </div>
          <div className="divide-y divide-ink-100">
            {suggestions.map(s => (
              <SuggestionRow key={s.id} suggestion={s}
                productById={productById}
                competitorById={competitorById}
                isManager={isManager}
                onRefresh={refreshSug}/>
            ))}
          </div>
        </Card>
      )}

      {!aL && !sL && autoLinks.length === 0 && suggestions.length === 0 && (
        <div className="text-[11.5px] text-ink-500 text-center mt-4">
          Everything reviewed. Trigger a fresh URL find from the Products page (✨ icon) to generate new suggestions.
        </div>
      )}
    </div>
  )
}

/* ── Auto-found URL row: URL editable inline, Accept / Reject ─────── */
function AutoLinkRow({ link, product, competitor, isManager, onChanged }) {
  const [urlDraft, setUrlDraft] = useState(link.url)
  const [editing, setEditing] = useState(false)
  const [busy, setBusy] = useState(null)   // null | 'saving-url' | 'accepting' | 'rejecting'
  const [err, setErr] = useState('')

  useEffect(() => { setUrlDraft(link.url) }, [link.url])

  const saveUrl = async () => {
    if (urlDraft.trim() === link.url.trim()) { setEditing(false); return }
    setBusy('saving-url'); setErr('')
    const { error } = await supabase.from('competitor_products')
      .update({ url: urlDraft.trim() })
      .eq('id', link.id)
    setBusy(null)
    if (error) { setErr(normaliseError(error)); return }
    setEditing(false)
    onChanged?.()
  }

  const accept = async () => {
    setBusy('accepting'); setErr('')
    // Change match_method to 'manual' → removes from this queue
    const { error } = await supabase.from('competitor_products')
      .update({ match_method: 'manual', match_confidence: 1.0 })
      .eq('id', link.id)
    setBusy(null)
    if (error) { setErr(normaliseError(error)); return }
    onChanged?.()
  }

  const reject = async () => {
    if (!confirm(`Delete this link (URL will not be scraped)?`)) return
    setBusy('rejecting'); setErr('')
    const { error } = await supabase.from('competitor_products').delete().eq('id', link.id)
    setBusy(null)
    if (error) { setErr(normaliseError(error)); return }
    onChanged?.()
  }

  return (
    <div className="px-6 py-4 hover:bg-canvas-100/40 transition-colors">
      <div className="flex items-start justify-between gap-4 flex-wrap">
        <div className="flex-1 min-w-0">
          {/* Header: badge + confidence */}
          <div className="flex items-center gap-2 mb-2">
            <Badge variant="amber">
              Auto-found · {link.match_confidence ? `${Math.round(link.match_confidence * 100)}%` : 'review'}
            </Badge>
            <span className="text-[10.5px] text-ink-500">
              {new Date(link.created_at).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })}
            </span>
          </div>

          {/* Grid: your product on left, competitor URL on right */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {/* Left: your product */}
            <div>
              <div className="text-[10px] uppercase tracking-[0.12em] font-semibold text-ink-500 mb-1.5 inline-flex items-center gap-1">
                <Package size={10}/> Your product
              </div>
              <div className="flex items-start gap-2.5">
                {product?.image_url ? (
                  <img src={product.image_url} alt=""
                    className="w-11 h-11 rounded-lg object-cover border border-ink-100 flex-shrink-0"
                    onError={e => { e.target.style.display = 'none' }}/>
                ) : (
                  <div className="w-11 h-11 rounded-lg bg-canvas-100 border border-ink-100 flex items-center justify-center text-ink-400 flex-shrink-0">
                    <Package size={16} strokeWidth={1.5}/>
                  </div>
                )}
                <div className="min-w-0">
                  <div className="text-[13px] font-semibold text-ink-900 truncate">{product?.name || '—'}</div>
                  <div className="text-[10.5px] font-mono text-ink-500 mt-0.5">{product?.sku}</div>
                  {product?.current_price != null && (
                    <div className="text-[11px] text-ink-600 mt-0.5 tabular-nums">
                      Your KD {Number(product.current_price).toFixed(3)}
                    </div>
                  )}
                </div>
              </div>
            </div>

            {/* Right: competitor URL (editable inline) */}
            <div>
              <div className="text-[10px] uppercase tracking-[0.12em] font-semibold text-ink-500 mb-1.5 inline-flex items-center gap-1">
                <Building2 size={10}/> Found on {competitor?.name || `#${link.competitor_id}`}
              </div>
              <div className="flex items-start gap-2.5">
                {link.image_url ? (
                  <img src={link.image_url} alt=""
                    className="w-11 h-11 rounded-lg object-cover border border-ink-100 flex-shrink-0"
                    onError={e => { e.target.style.display = 'none' }}/>
                ) : (
                  <div className="w-11 h-11 rounded-lg bg-canvas-100 border border-ink-100 flex items-center justify-center text-ink-400 flex-shrink-0">
                    <Package size={16} strokeWidth={1.5}/>
                  </div>
                )}
                <div className="min-w-0 flex-1">
                  <div className="text-[13px] font-semibold text-ink-900 truncate">{link.name}</div>
                  {editing ? (
                    <div className="flex items-center gap-1 mt-1">
                      <input
                        type="url"
                        value={urlDraft}
                        onChange={e => setUrlDraft(e.target.value)}
                        onKeyDown={e => { if (e.key === 'Enter') saveUrl(); if (e.key === 'Escape') { setUrlDraft(link.url); setEditing(false) } }}
                        autoFocus
                        className={`${inputCls} py-1 text-[11px] font-mono`}
                        placeholder="https://…"
                      />
                      <button onClick={saveUrl} disabled={busy === 'saving-url'}
                        className="p-1 rounded text-emerald-700 hover:bg-emerald-50 disabled:opacity-50">
                        <Check size={13}/>
                      </button>
                      <button onClick={() => { setUrlDraft(link.url); setEditing(false) }}
                        className="p-1 rounded text-ink-500 hover:bg-ink-100">
                        <XIcon size={13}/>
                      </button>
                    </div>
                  ) : (
                    <div className="flex items-center gap-2 mt-1">
                      <a href={link.url} target="_blank" rel="noopener noreferrer"
                        className="text-[11px] font-mono text-brand-700 hover:underline inline-flex items-center gap-1 truncate flex-1 min-w-0">
                        <span className="truncate">{link.url}</span>
                        <ExternalLink size={9} className="flex-shrink-0"/>
                      </a>
                      {isManager && (
                        <button onClick={() => setEditing(true)}
                          title="Edit URL"
                          className="p-1 rounded text-ink-400 hover:text-brand-700 hover:bg-brand-50 flex-shrink-0">
                          <Pencil size={11}/>
                        </button>
                      )}
                    </div>
                  )}
                </div>
              </div>
            </div>
          </div>

          {err && (
            <div className="mt-3 text-[11.5px] text-red-800 bg-red-50 border border-red-100 rounded-lg px-2.5 py-1.5">
              {err}
            </div>
          )}
        </div>

        {/* Action buttons */}
        {isManager && (
          <div className="flex flex-col gap-2 flex-shrink-0">
            <Button variant="gold" size="sm" busy={busy === 'accepting'} onClick={accept} disabled={editing}>
              <CheckCircle2 size={13}/> Accept
            </Button>
            <Button variant="secondary" size="sm" busy={busy === 'rejecting'} onClick={reject} disabled={editing}>
              <XIcon size={13}/> Reject
            </Button>
          </div>
        )}
      </div>
    </div>
  )
}

/* ── Legacy pg_trgm suggestion row ────────────────────────── */
function SuggestionRow({ suggestion, productById, competitorById, isManager, onRefresh }) {
  const [busy, setBusy] = useState(false)

  const accept = async () => {
    setBusy(true)
    await supabase.from('competitor_products')
      .update({ product_id: suggestion.product_id, match_method: 'auto', match_confidence: suggestion.confidence })
      .eq('id', suggestion.competitor_product_id)
    await supabase.from('match_suggestions')
      .update({ reviewed: true, accepted: true })
      .eq('id', suggestion.id)
    setBusy(false); onRefresh()
  }

  const reject = async () => {
    setBusy(true)
    await supabase.from('match_suggestions')
      .update({ reviewed: true, accepted: false })
      .eq('id', suggestion.id)
    setBusy(false); onRefresh()
  }

  const p = productById[suggestion.product_id]

  return (
    <div className="px-6 py-4 hover:bg-canvas-100/40 transition-colors flex items-start justify-between gap-4">
      <div className="flex-1 min-w-0">
        <Badge variant="amber">{Math.round(suggestion.confidence * 100)}% match</Badge>
        <div className="mt-2 text-[13px] text-ink-800">
          Link competitor product #{suggestion.competitor_product_id} → <span className="font-semibold text-ink-900">{p?.name || `product #${suggestion.product_id}`}</span> <span className="font-mono text-[10.5px] text-ink-500">({p?.sku})</span>
        </div>
      </div>
      {isManager && (
        <div className="flex flex-col gap-2 flex-shrink-0">
          <Button variant="primary" size="sm" busy={busy} onClick={accept}>
            <CheckCircle2 size={13}/> Accept
          </Button>
          <Button variant="secondary" size="sm" busy={busy} onClick={reject}>
            <XIcon size={13}/> Reject
          </Button>
        </div>
      )}
    </div>
  )
}
